# Generated by Django 3.1.3 on 2021-01-08 12:36

import bikes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=10)),
                ('image', models.ImageField(default='default.png', upload_to='pics/')),
                ('age', models.IntegerField(default=18)),
                ('phno', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeid', models.CharField(max_length=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('bikemodel', models.CharField(choices=[('Pulsar 220 F', 'Pulsar 220 F'), ('Platina 100', 'Platina 100'), ('Bajaj CT 100', 'Bajaj CT 100'), ('Glamour BS6', 'Glamour BS6'), ('Xtreme 200S', 'Xtreme 200S'), ('Destini 125 BS6', 'Destini 125 BS6'), ('HondaShine', 'HondaShine'), ('Honda Dio', 'Honda Dio'), ('Honda Active', 'Honda Active'), ('Bullet350', 'Bullet350'), ('Enfield Classic 350', 'Enfield Classic 350'), ('Enfield Meteor 350', 'Enfield Meteor 350')], max_length=40)),
                ('bikefrontimage', models.ImageField(upload_to='modelbikes/')),
                ('bikelocation', models.CharField(max_length=100)),
                ('ordername', models.CharField(max_length=30)),
                ('expecteddate', models.DateField(null=True)),
                ('tracking', models.CharField(choices=[('Delivered', 'Delivered'), ('pending', 'pending'), ('Rejected', 'Rejected')], default='awiting', max_length=50)),
                ('deliveryaddress', models.CharField(max_length=200)),
                ('documenttype', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to=bikes.models.content_file_name)),
                ('comments', models.CharField(max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddBike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikemodel', models.CharField(choices=[('Pulsar 220 F', 'Pulsar 220 F'), ('Platina 100', 'Platina 100'), ('Bajaj CT 100', 'Bajaj CT 100'), ('Glamour BS6', 'Glamour BS6'), ('Xtreme 200S', 'Xtreme 200S'), ('Destini 125 BS6', 'Destini 125 BS6'), ('HondaShine', 'HondaShine'), ('Honda Dio', 'Honda Dio'), ('Honda Active', 'Honda Active'), ('Bullet350', 'Bullet350'), ('Enfield Classic 350', 'Enfield Classic 350'), ('Enfield Meteor 350', 'Enfield Meteor 350')], max_length=40)),
                ('cost', models.FloatField(null=True)),
                ('company', models.CharField(choices=[('Bajaj', 'Bajaj'), ('Hero', 'Hero'), ('Honda', 'Honda'), ('RoyalEnField', 'RoyalEnField')], max_length=30)),
                ('companybrand', models.ImageField(upload_to='company/')),
                ('bikefrontimage', models.ImageField(upload_to='modelbikes/')),
                ('bikebackimage', models.ImageField(upload_to='modelbikes/')),
                ('bikerightimage', models.ImageField(upload_to='modelbikes/')),
                ('bikeleftimage', models.ImageField(upload_to='modelbikes/')),
                ('bikelocation', models.CharField(max_length=100)),
                ('fueltype', models.CharField(choices=[('Petrol', 'Petrol'), ('Electric', 'Electric')], max_length=20)),
                ('noofgears', models.CharField(choices=[('4', '4'), ('5', '5')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
