# Generated by Django 3.1.3 on 2021-01-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20210111_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbike',
            name='noofgears',
            field=models.CharField(choices=[('0', '0'), ('4', '4'), ('5', '5')], max_length=5),
        ),
    ]
